### ISSUE TITLE
fly-cssnano is completely breaking local fly (with babel@6)

### ISSUE THREAD

**Issue by icflorescu** [ben-eb/fly-cssnano#1]
`fly` fails completely when `fly-cssnano` is installed, most likely due to a breaking change in babel@6:

    192-168-0-103:test-fly ionut$ ./node_modules/.bin/fly production
    stack: 
      - TypeError: Cannot read property 'filter' of undefined
      -     at Fly.module.exports (/Volumes/Data/Work/Web/test-fly/node_modules/fly-cssnano/index.js 6:5)
      -     at /Volumes/Data/Work/Web/test-fly/node_modules/fly/dist/fly.js 113:14
      -     at Array.forEach (native)
      -     at new Fly (/Volumes/Data/Work/Web/test-fly/node_modules/fly/dist/fly.js 108:13)
      -     at Object.spawn$ (/Volumes/Data/Work/Web/test-fly/node_modules/fly/dist/cli/spawn.js 38:45)
      -     at tryCatch (/Volumes/Data/Work/Web/test-fly/node_modules/babel-runtime/regenerator/runtime.js 67:40)
      -     at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/Data/Work/Web/test-fly/node_modules/babel-runtime/regenerator/runtime.js 315:22)
      -     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Volumes/Data/Work/Web/test-fly/node_modules/babel-runtime/regenerator/runtime.js 100:21)
      -     at onFulfilled (/Volumes/Data/Work/Web/test-fly/node_modules/co/index.js 65:19)
    message: Cannot read property 'filter' of undefined

I'll get back with a simple PR in a few minutes.

**Comment by ben-eb** [comment]
I wonder if this ever worked, as I don't rely on babel to compile this module...

**Comment by icflorescu** [comment]
I'm not sure, it's the first time I gave it a try, but `fly` fails completely when trying to run it locally (`./node_modules/.bin/fly`) in this simple scenario:

`package.json`:

    {
      "name": "test-fly",
      "version": "1.0.0",
      "devDependencies": {
        "babel-core": "^6.0.16",
        "babel-loader": "^6.0.1",
        "babel-preset-es2015": "^6.0.15",
        "fly": "^0.8.3",
        "fly-cssnano": "^1.1.0",
        "fly-stylus": "^0.5.0",
        "fly-uglify": "^1.0.0",
        "fly-webpack": "^1.0.9"
      }
    }

I assume it might have something to do with babel 6 deps in my project. Haven't tried it with global `fly`, but I'm sure more people will bump into this eventually.

The PR is actually a dead simple one, the only thing I did was change this:

    module.exports = () => {

to:

    module.exports = function () {

and everything works as expected.

**Comment by icflorescu** [comment]
It does work with **global** fly, but breaks when trying to use **local** fly in the above configuration.

AFAIK it's good practice to use `fly` locally in your project, so I'm guessing it's just a matter of time till other people transpiling client-side code with `babel` will run into this issue.
